kind = "web"
previewPath = "/"
title = "مسابَقة مُصلِح"
version = "1.0.0"
id = "artifacts/mislah"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24796

[services.development]
run = "pnpm --filter @workspace/mislah run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mislah", "run", "build" ]
publicDir = "artifacts/mislah/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24796"
BASE_PATH = "/"
